lib/wefood_web/router.ex
defmodule WefoodWeb.Router do
  use WefoodWeb, :router

  import WefoodWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WefoodWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WefoodWeb do
    pipe_through :browser

    live_session :create_cart_session, on_mount: LiveSession.Cart do
      live "/", MainLive, :index
      live "/cart", CartLive, :index
    end
  end

  # coveralls-ignore-start

  # Other scopes may use custom stacks.
  # scope "/api", WefoodWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: WefoodWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  # coveralls-ignore-stop

  ## Authentication routes

  scope "/", WefoodWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", WefoodWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live_session :is_admin, on_mount: {LiveSessions.Permissions, :admin} do
      scope "/admin", Admin, as: :admin do
        live "products", ProductLive, :index
        live "products/new", ProductLive, :new
        live "products/:id/edit", ProductLive, :edit
        live "products/:id/delete", ProductLive, :delete
        live "products/:id", ProductLive.Show, :show
      end
    end
  end

  scope "/", WefoodWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/wefood_web/controllers/user_registration_controller.ex
defmodule WefoodWeb.UserRegistrationController do
  use WefoodWeb, :controller

  alias Wefood.Accounts
  alias Wefood.Accounts.User
  alias WefoodWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/wefood_web/views/user_registration_view.ex
defmodule WefoodWeb.UserRegistrationView do
  use WefoodWeb, :view
end

lib/wefood_web/templates/user_registration/new.html.heex
<section class="login flex justify-center pt-4">
<div class="w-full mx-w-xs">
<h1>Register</h1>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)} class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

<div class="mb-4">
  <%= label f, :email, class: "block-text-gray-700 text-sm font-bold mb-2" %>
  <%= email_input f, :email, required: true, placeholder: "email", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  <%= error_tag f, :email %>
</div>

<div class="mb-4">
  <%= label f, :password, class: "block-text-gray-700 text-sm font-bold mb-2" %>
  <%= password_input f, :password, required: true, placeholder: "*********", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  <%= error_tag f, :password %>
</div>

  <div class="flex-items-center justify-between">
    <%= submit "Register", class: "btn-primary rounded-full text-sm text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
</.form>

<p>
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
</p>
</div>
</section>